### ISSUE TITLE
[Bug]: `shopify theme dev` - localhost:9292 shows CORS issues when fonts are used on CSS files

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#1103]
### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Fonts should be served by a `localhost` URL:

![image](https://user-images.githubusercontent.com/1079279/212643140-194b1528-3637-45a9-9e2c-60cc89a64a34.png)

### Actual behavior

Fonts are being served by `fonts.shopifycdn.com` when they are used on CSS files

![image](https://user-images.githubusercontent.com/1079279/212643262-2b2d8b30-0baf-4b05-8b8c-d3cb886a3e6b.png)

Source: https://shopifypartners.slack.com/archives/CKQTKDZV2/p1673536569637039

### Reproduction steps

1. Use a font in a CSS file
2. Open http://localhost:9292/
3. Notice that CORS issues happen

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.11

### What language and version are you using in your application?

3.1

**Comment by anteksiler** [comment]
I am getting the same error on CLI version 3.36.1

**Comment by Poitrin** [comment]
@ceri-waterscreative, @anteksiler, @blanklob
As I was not able to reproduce the issue, can you share additional instructions? 😊

Here's what I did (FYI, I used `shopify theme init` to create a new Dawn-based theme):

As plain `.css` files do not support Liquid code, I interpreted the reproduction step "Use a font in a CSS file" as…
1. Create `assets/fonts.css.liquid` with content from `theme.liquid`
    ```liquid
    {%- liquid
    assign body_font_bold = settings.type_body_font | font_modify: 'weight', 'bold'
    assign body_font_italic = settings.type_body_font | font_modify: 'style', 'italic'
    assign body_font_bold_italic = body_font_bold | font_modify: 'style', 'italic'
    %}
    
    {{ settings.type_body_font | font_face: font_display: 'swap' }}
    {{ settings.type_header_font | font_face: font_display: 'swap' }}
    {{ body_font_bold | font_face: font_display: 'swap' }}
    {{ body_font_italic | font_face: font_display: 'swap' }}
    {{ body_font_bold_italic | font_face: font_display: 'swap' }}
    ```
    and make sure that no font (referenced via `settings`) is loaded in `theme.liquid`.
2. Let `theme.liquid` include `fonts.css.liquid` via
    ```html
    <link type="text/css" href="{{ 'fonts.css' | asset_url }}" rel="stylesheet">
    ```

These two steps should also fit the [scenario mentioned in the Partners Slack channel](https://shopifypartners.slack.com/archives/CKQTKDZV2/p1673536569637039) 
> In this scenario it's via an off the shelf theme. Just being loaded in the css.liquid via:
> {{ settings.type_menu | font_face: font_display: fonts_type_menu_display }}
> I think the issue persists with ours as well where we do it via <link rel="" />

No CORS error appeared.
![07-03-m4jq9-h7n03](https://user-images.githubusercontent.com/12963280/223445026-f2b7d9f0-c8ee-4283-91ac-c2ad55a6e3ae.jpg)
`307 Internal Redirect` is due to `http` → `https`.

**Comment by blanklob** [comment]
@Poitrin I merged everything is working well now thanks.
