### ISSUE TITLE
Create a table component in the CLI UI Kit

### ISSUE THREAD

**Issue by MeredithCastile** [Shopify/cli#1143]
Right now, devs working on the Shopify CLI must create tables from scratch. @Poitrin has, for instance, created a table to display theme-related information in the command line.

To state the obvious, a table is an efficient way to display scannable structured data. But getting them right on the command line is important and not altogether easy. (Ex: What happens if the terminal window is extremely narrow? What happens if a line is much longer than the rest? The gutter between columns should be, what, 3 characters?)

Can we create a flexible but time-saving component for the CLI UI Kit? Do we have enough potential use-cases to justify that effort?

**Comment by matteodepalo** [comment]
Can we just close this or is not feature complete enough?

**Comment by MeredithCastile** [comment]
I didn't realize you'd created a table component already, @matteodepalo. What are the rules around it?

**Comment by Poitrin** [comment]
I implemented the table based on [@karreiro’s prototype](https://docs.google.com/document/d/1XcYSld4xr6ltetES2v39-zuR8OLHkcZThas1j_OY-lY/edit#bookmark=id.x8rno9r81z7o):

![20-37-wvyta-bajp9](https://user-images.githubusercontent.com/12963280/213642200-e1c43cbe-47d3-4017-ac3b-1ca950ac2460.jpg)

`ink`’s `<Box />` component already seems to be able to display data "more or less correctly" on small screens.
Long lines are also covered by `ink` already, [see screenshot](https://github.com/Shopify/cli/pull/1040#pullrequestreview-1240963775).

A table working similar to UNIX’ `ls` command or [jQuery Datatables](https://datatables.net/) (i.e. list on small widths, table on large widths) could solve the issue, but it’s of course more effort, and for the moment, I don't see enough potential use-cases to justify that effort.

**Comment by karreiro** [comment]
> Can we just close this or is not feature complete enough?

Personally, I agree we could close this issue, as I believe the current component implementation good enough for themes (`shopify theme list` doesn't have too many columns and the sizes of `role` and `id` are predictable).

> What happens if the terminal window is extremely narrow? What happens if a line is much longer than the rest? The gutter between columns should be, what, 3 characters?

I also believe that this points are valuable reflections, because this component might be used on contexts with too many columns and maybe need to support values with more unpredictable number of characters.

With that in mind, we may decide to present this component differently depending of the viewport.

Still, I'm not sure if it's a good idea to tackle this problem now or when a scenario with more complex tables emerge. Both seem fair approaches :)

**Comment by matteodepalo** [comment]
Good points. Personally I'd like to wait until we need it before we deal with edge cases. For now the component we have is more than good enough IMHO.
