### ISSUE TITLE
[Feature]: Linting by default

### ISSUE THREAD

**Issue by ChaseWNorton** [Shopify/cli#137]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

Since Shopify is attempting to provide a batteries included scaffolding solution - the lack of linting seems like a miss.  In addition, with the new folder structure - linting and multiple linting configs creates a multi hour setup process. 

### Motivation

Shopify seems to think developers want more abstraction. While Jr devs may want this - this causes increased confusion for devs that want to know what the heck is going on. That said - if you are going to try to abstract away everything, considering adding a linting process built in so devs don't need to add additional time configuring eslint

**Comment by shauns** [comment]
Hi @ChaseWNorton -- to better understand this one, can I check a couple of assumptions:

- you've got an app with both `web` and `extensions`
- these share a common language, i.e. all written in JS, and hence common tooling
- you'd like to more easily run `eslint` across all the elements of your app in one go, instead of per-extension + `web` separately

And then as an aside for more background -- how were you managing your app prior to CLI3.0? Separate repos/workspaces/something else?
