### ISSUE TITLE
[Bug]: CLI is trying too hard here

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1475]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The App should just start

### Actual behavior

It started, but I see some logs that are interesting. 

Sending APP_UNINSTALLED webhook to app server
2023-02-28 18:43:46 | webhooks | App isn't responding yet, retrying in 5 seconds

So that is interesting. It does not work for whatever reason, but hey, nice try! 

The App has a job for app/uninstalled in the store. But when starting up this time, in a migration to CLI 3, the CLI has this issue. It is benign sure, but also annoying. The only thing in the start-up logs that gives a clue to this is the following:

     Using a different app than last time, sending uninstall webhook to app server

What does that even mean? I see this App is installed in exactly one test shop, the one I specified using the CLI. Seems like either you have a timing issue, or something else is logically busted? 

Anyway, there you go. Have fun with that one. 

### Reproduction steps

1. migrate an App from no CLI to CLI 3
2. yarn run dev
3. profit

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

19.7

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by alvaro-shopify** [comment]
Hi @resistorsoftware . Thanks for bringing up this issue. 

That `webhook` was included in the case a developer uses 2 different apps with the same store locally, the app thinks it is already installed to the store. That happens because the database entry isn't associated with the app itself, so the app decides it's installed even if it isn't actually installed in Shopify.

To help ensure that the app starts with a fresh state, the CLI will now send an app/uninstalled webhook to the app after it starts, so that it can clean up the state for the store, and reinstall an app if it changes.

This only happens if and only if:
- the user has just selected a new app, either by running dev --reset or passing in a different --api-key flag
- the app has a new webhooks_path value in their backend shopify.web.toml file

I hope that this explanation can clarify a bit that log messages.

**Comment by resistorsoftware** [comment]
Hi,

In my case, the App selected was installed on the store in question, the developer store I selected for running the App. I could tell this by simply looking at the dates of the install from the Partner Dashboard for the App keypair. 

So I had not selected a new App per se, but since this was a migration from CLI 2 days, I guess the trigger here was, the CLI 3 connector had not seen the API keys before, how could it? All new to it. So that is the reason for this? Maybe inform the developer that a migration to CLI 3 could be in play (it was) so that messaging makes more sense? 

All good. Thanks for the update.
