### ISSUE TITLE
[Bug]: shopify app deploy 504 error

### ISSUE THREAD

**Issue by mitchelldirt** [Shopify/cli#1548]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Should ask me if I want to deploy and then show the rainbow loading bar when I say yes.

### Actual behavior

npm run deploy

> code-splitting-example@1.0.0 deploy
> shopify app deploy

╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                      │
│                                                                                                                                      │
│    The Partners GraphQL API responded unsuccessfully with the HTTP status 504 and errors:                                            │
│                                                                                                                                      │
│    {}                                                                                                                                │
│                                                                                                                                      │
│                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Stack trace

```shell
{}
```

### Reproduction steps

1. npm run deploy

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

Warp

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Node 18.12.1 (Should be the same node version I'm running?)

**Comment by mitchelldirt** [comment]
Whoops - looks like it's now working, waited like 10 minutes and it worked :)

**Comment by rajmasha** [comment]
We have been facing the same issue since 9th Aug 2024(last 5 days). 
If we reduce the number of extensions from 27 to 13 then we are able to deploy successfully. So, it seems that there is some limit that has been added from Shopify's end which is preventing deploying many extensions. 

### Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli). - **Yes (CLI version: 3.65.3)**

### In which of these areas are you experiencing a problem?
Extension

### Expected behavior
The shopify app deploy command should successfully deploy all extensions

### Actual behavior
The shopify app deploy command kept showing the rainbow loader for a while and then failed with an error

```
The Partners GraphQL API responded unsuccessfully with the HTTP status 504
  and errors:

{}

Request ID: c6b817e8-5c82-4381-92e2-51da24c7b1c7-1723533914
```

### Stack trace
{}

### Reproduction steps
npm run deploy

### Operating System
Mac OS Sonoma 14.4.1

### Shopify CLI version (check your project's package.json if you're not sure)
3.65.3

### Shell
zsh

### Node version (run node -v if you're not sure)
20.12.2

### What language and version are you using in your application?
```
"react": "^18.0.0",
"typescript": "^3.9.7"
```
