### ISSUE TITLE
[Feature]: Command Line Tips (About Shopify API Deprecation Tips)

### ISSUE THREAD

**Issue by forwells** [Shopify/cli#156]
### What area(s) will this request affect?

App, Running your code locally, Other

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Notice level reminder of api deprecation is always going on in the command line console whenever developing
![image](https://user-images.githubusercontent.com/32950945/178944164-7fd403a8-fb5f-4e0f-81da-095ebf06487b.png)

### Motivation

When I keep seeing API deprecation reminders in the CLI, I always think that I have some API requests that are not normal or maybe even using a deprecated API.
This is very unpleasant, I even tried to read the source code of Shopify/cli 3.0, but I am not good at cli development, so I hope the new cli of shopify can solve this prompt in subsequent versions~

**Comment by gonzaloriestra** [comment]
Thanks for the suggestion!

@andyw8 do you think this is something we could improve in the templates?

**Comment by paulomarg** [comment]
Hey folks! That information is logged whenever a query receives a deprecation header, [as per the docs](https://shopify.dev/api/usage/versioning#rest-api-deprecation-practices). The idea behind logging it is to encourage folks to fix any deprecated queries, because Shopify might reject apps that make them.

Unfortunately, the header doesn't include information on which query is failing for the GraphQL API, but we can make it easier to spot which query is failing by adding some of the body to that logging. I'll set up a PR that does that, but the logging should probably stay there as it is meant to be a reminder that something needs to be fixed.
