### ISSUE TITLE
[Feature]: Authorize and associate a Shopify embed app or extension with a Partner account or organization without having to run shopify app dev or shopify app deploy

### ISSUE THREAD

**Issue by vlad-mb** [Shopify/cli#1793]
### What area(s) will this request affect?

App, Extension, Running your code locally

### What type of change do you want to see?

New feature

### Overview

I want to create an embed application or an extension, and at the same time creating a new app on the Shopify Side (associated with my Partner account or organization) with associating the project with it.

In that case it could be helpful to have additional flags for it.

### Motivation

I have a custom code which makes the process of creating and then modifying the apps with Shopify CLI easier. In that case I have to follow these steps:
1. Create a new embed app with `yarn create @shopify/app --template node`

2. Use `yarn shopify app dev` to run it for the first time, to authorize with browser.
According to Shopify Dev documentation, this command (or `yarn shopify app deploy`) creates a new app associated with my Partner account or organization and associate my local app with it.

https://shopify.dev/docs/apps/tools/cli/commands#dev
https://shopify.dev/docs/apps/tools/cli/commands#deploy

3. Then I request the env variables (the Shopify key && the secret key) for the new app using `yarn shopify app env pull`.

So the questions:
a) Is there any opportunity to log in with Shopify CLI on the first step, when creating the app? In that case we would use the same flags (`--api-key, --tunnel-url, --store`) as for the `yarn shopify app dev` command.
b) In the case I am logged in, is there any opportunity to create a new app associated with my Partner account or the organization immediately when creating i.e. embedded app with `yarn create @shopify/app --template node`? In that case the additional flags could be needed.

**Comment by alvaro-shopify** [comment]
Hi @vlad-mb!. First of all, thank you for your proposal.

The `create-app` operation has been designed to be an `unauthenticated` command intentionally. The main objetives of that are:
- Quick operation to scaffold as quick as possible a new application
- Working with the app without having to create a partners account

That's why the cli delay the authentication process to the commands that really need to connect to a remote app. And it's at that point when the user can create a new application to associate to your local app

I hope that this explanation make sense to you. Anyway, please, feel free to add more context to this requirement just in case we are missing something.

Looking forward to hear from you soon.
