### ISSUE TITLE
[Feature]: Tailscale Serve support for tunnels

### ISSUE THREAD

**Issue by SaphireLattice** [Shopify/cli#2257]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

Substantial change to existing feature

### Overview

It would be nice to add an integration with Tailscale Serve/Funnel as it would allow developers who have Tailscale to use existing infrastructure. It would also reduce the need to set the app URL every time the app is restarted.

Relevant documentation: https://tailscale.com/kb/1242/tailscale-serve/, though I am not sure if there's any API for using that. There's also [tsnet](https://tailscale.com/kb/1244/tsnet/), but that is a Go library for integration with Go programs.

### Motivation

Biggest issue I have faced when using shopify-cli with ngrok is that the URL sometimes does not get updated in the control panel, and that it changes every time I restart the session for one reason or another. Even if I don't need to do it often, it's still a frustrating experience.

**Comment by gonzaloriestra** [comment]
Hi! Thanks for the suggestion.

Since v3.45.0 the CLI uses [Cloudflare Quick Tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/trycloudflare/) by default. And you can still use Ngrok by passing `--tunnel ngrok`.

If you want to use another tunneling solution, you can run the dev command with a custom URL with `--tunnel-url`. That way, you can always use the same URL. More info here:
https://shopify.dev/docs/apps/tools/cli/commands#dev-flags

Having that flexibility, we are not planning to add any other tunnel provider for now, so I'm closing here.

**Comment by SaphireLattice** [comment]
Nice to know about `--tunnel-url`, thanks! Guess I've missed that somehow. This sounds like a fitting and acceptable alternative.

**Comment by LovesTha** [comment]
Would be nice to have the config for using tailscale funnels documented somewhere... (this thread is the only search hit for `"tailscale" "funnel" "shopify"`)
