### ISSUE TITLE
[Bug]: "run deploy" push the extension to base version

### ISSUE THREAD

**Issue by imprintnext-debashis** [Shopify/cli#2735]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Deploys done for the app extensions should have been pushed to the latest versions. However, my deployments are reflected on 3b6as66e versions that are 0.0.0
Hence, 

### Actual behavior

when the extension is loaded for the end users It loads scripts from extension version 1.0.0 (latest) and I am not able to alter it. The latest deploys of scripts always go to the base version (0.0.0) which only loads for development stores of Shopify and not the live stores

### Reproduction steps

1. Open [this product link](https://performance-rpo.myshopify.com/products/the-collection-snowboard-liquid) and storefront password is -  iantay
2. In the console when you look for our extension script it loads from [this CDN URL](https://cdn.shopify.com/extensions/6ba6387b-4779-4b78-ba66-8b3fcf7f4d28/0.0.0/assets/rpo-product-options.js?v=1692010707) which is from base version 0.0.0 but it loads our latest deployed code
3. Now when a real Shopify store or Shopify reviewers install our app extension, the script loads from 1.0.0 (changes in the given URL above) which is the latest version of our extension but our deployed scripts won't reflect there.

![Screenshot_090123_115050_AM](https://github.com/Shopify/cli/assets/18134050/ce7c7b1c-8e77-4598-a97c-3ea239690256)

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.4

### Node version (run `node -v` if you're not sure)

v18.16.0

**Comment by amcaplan** [comment]
Hi @imprintnext-debashis, thanks for getting in touch!

Is it possible you have development preview mode enabled on your test store? That would cause the latest pushed version (by `dev`) to appear on your development stores, rather than the version most recently released.

This mode doesn't affect live stores, which will used the actual released version of your app, including the theme app extension.

**Comment by imprintnext-debashis** [comment]
This issue is still relevant.

**Comment by isaacroldan** [comment]
Hi @imprintnext-debashis, i'm going to close this issue since we've changed how deploys and dev-preview works, since version 3.48 we have "Unified Deployments" and the dev-preview is a toggle per-store and not per-extension.

Hopefully the issue has been solved for you, as a summary:
- When you have dev-preview enabled in a store, you'll see the latest drafts of each extension instead of the latest published versions. (when running `app dev` from the CLI, we automatically enable dev-preview for the selected store)
- If dev-preview is disabled in a store, you will always see the latest published version of the extensions.
