### ISSUE TITLE
[Bug]: `shopify theme console` always outputs an error

### ISSUE THREAD

**Issue by blanklob** [Shopify/cli#2811]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

To work.

### Actual behavior

Here is the loom explains everything:

https://www.loom.com/share/6968646e89be4c4fbaccb6caac3b9c64?sid=5611a797-a170-49cf-8f35-69f589d3bf00

### Reproduction steps

1. Check this starter I used: https://github.com/odestry/theme-starter
2. Install dependencies
3. Run the command

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.x.x

### What language and version are you using in your application?

Ruby 3

**Comment by karreiro** [comment]
Thank you for reporting this issue, @blanklob. Also, we truly appreciate the video you recorded; it's incredibly helpful in understanding the root cause of the problem.

You can workaround this issue by executing the following command:
```bash
shopify theme delete -f -t liquid-console-repl
```

Once you've run that command, `shopify theme console` is going to work as expected.

### Additional Context

The issue you're encountering stems from the fact that `shopify theme console` depends on a small hidden theme named `liquid-console-repl` (you don't need a theme on your machine to execute this command).

However, since you tested the beta version of `shopify theme console`, your store ended up with an outdated version of `liquid-console-repl`.

I'm currently working on a solution to ensure that anyone with an outdated `liquid-console-repl` won't encounter this problem in the future. But, for now, you may avoid the problem by relying in the workaround above.

--

Thanks again for reporting this!
