### ISSUE TITLE
[Bug]: When loading fonts via asset_url or file_url, the fonts are loaded from localhost/cdn instead of shopify/cdn

### ISSUE THREAD

**Issue by ineptian** [Shopify/cli#2856]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Should load fonts from `//augusta-and-adeline.myshopify.com/cdn/` and not `//localhost/cdn/`

### Actual behavior

Fonts are trying to load from  `//localhost/cdn/` which does not exist.

### Reproduction steps

1. Create an @font face rule: `src: url("{{ 'font.name' | asset_url }}") format("woff2")`
2. Get the error.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

### Shell

powershell

### Node version (run `node -v` if you're not sure)

18.17.1

**Comment by vfxjohow** [comment]
Hello!

I do have the same issue for a longer time now. The custom fonts are not loading when I run the theme locally, but when I open the preview on the cloud it works as expected. It seems to happen since a CLI Update. 

Here you can see the fonts are loading from local host in the source code:
![grafik](https://github.com/Shopify/cli/assets/52751209/e1cb7c77-67d9-4d31-98ac-8e594ae1b4c3)

But in the console I do receive a CORS error while trying to load the font from the Shopify CDN:
![grafik](https://github.com/Shopify/cli/assets/52751209/924245e0-8c1f-4035-9f94-0ed76bbc1225)

I don't know why it is mixed up that way and hope this info helps to solve the issue.

**Comment by vaishnavi-s2901** [comment]
the same issue was happening with only firefox dev edition, and now after update its happening with chrome too

**Comment by vfxjohow** [comment]
Oh, yes in Firefox it seems to be even more difficult. There are JS files also not loading anymore:

![grafik](https://github.com/Shopify/cli/assets/52751209/d8fd08ed-1e1f-4161-9da6-d9cb572996c5)

**Comment by ineptian** [comment]
> Custom fonts are loading as expected on my end from local. `@shopify/cli/3.49.3`
> 
> * [Firefox](https://imgur.com/a/TP32irm)
> * [Chrome](https://imgur.com/a/PZNhzFz)
> * [Safari](https://imgur.com/a/iOisBJV)

You are calling them using asset_url or using relative/absolute links? You can get them to work on local by defining their source absolutely but if you define them using liquid (the recommended way) it wont work.

**Comment by montalvomiguelo** [comment]
Hey @ineptian, I'm loading my custom font `LumierRegular` using the `asset_url` filter.

**Comment by ineptian** [comment]
> Hey @ineptian, I'm loading `LumierRegular.woff2` using the `asset_url` filter.

Are you sure the font is being loaded properly and you aren't just viewing a locally installed version of the font? For me it does not work. On windows. Not sure if that would make any difference.

**Comment by vfxjohow** [comment]
I have the presumption, that the issue is maybe initiated when you change the Shopify system and theme you are working on. 

For example, when you work for different customers on various Shopify systems. So maybe there is some kind of cache interfering here.

I can currently not reproduce it because the development themes stay active for one week and I need to work on different themes every day.

I will further observe the issue to clarify the reason for it.

**Comment by ineptian** [comment]
> I have the presumption, that the issue is maybe initiated when you change the Shopify system and theme you are working on.

I do work on quite a few different shopify sites and switch around frequently. I wonder if logging out completely and logging back in to shopify could possibly solve the issue. Will try next time I am working on it.

**Comment by vaishnavi-s2901** [comment]
i'm still facing this issue on both firefox and chrome.. i have tried logging out and logging back from shopify cli and that didn't work.. i also tried reinstalling shopify cli, but no luck..

**Comment by ineptian** [comment]
This still appears to be an issue.

**Comment by vfxjohow** [comment]
Still an issue.

**Comment by vfxjohow** [comment]
It is still an issue with the latest CLI version, is nobody taking care of it?

![grafik](https://github.com/Shopify/cli/assets/52751209/e42d5e4d-fe0f-43f5-99f8-4937f393f699)

**Comment by VedranCOI** [comment]
Still an issue.

**Comment by vfxjohow** [comment]
Just recognized that when I sync a development theme it uploads all files until 100%, but then it's uploading the custom fonts afterwards, so it looks like something is probably not in sync with all the other theme files here.

![Screenshot 2024-02-14 160349](https://github.com/Shopify/cli/assets/52751209/64e7cd0e-d580-42fe-bc54-b5153ca6a8d2)

**Comment by kevin-golo** [comment]
+1
