### ISSUE TITLE
[Bug]: Cannot connect Custom app to local Function extension app for Shopify Plus merchant

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#3201]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

After running `npm run dev`, I'm asked to select a Partner account and an app: new or connect to existing.
I choose to connect to existing app and then I'm presented with all the apps in my Partner account.

### Actual behavior

However, the app that I'm trying to deploy the Function to, is not in my Partner account, because it's a Custom app that is only available in the merchant's Shopify Plus store.

How can I deploy this Function to the Custom app on Shopify Plus store?

### Verbose output

```shell
/
```

### Reproduction steps

1. `npm init @shopify/app@latest`
2. `cd <app_dir>`
3. `npm run dev`

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.52.0

**Comment by amcaplan** [comment]
Hi @vfonic, I'm a bit confused by this:

> However, the app that I'm trying to deploy the Function to, is not in my Partner account, because it's a Custom app that is only available in the merchant's Shopify Plus store.

A [custom Partner app](https://help.shopify.com/en/manual/apps/app-types) always exists as part of a Partner account. You can then make it available to a merchant using a custom app install ink.

Are you talking about a [custom app generated in the Shopify admin](https://help.shopify.com/en/manual/apps/app-types/custom-apps)? If so, that's a different type of app entirely, and it's not eligible for extensions and functions. It's really just an access token that you can use to run background jobs and the like.

You can, of course, create a new app in your Partner account, deploy your function there, and then [create a custom app installation link](https://shopify.dev/docs/apps/distribution/select-distribution-method#install-a-custom-app-on-multiple-stores) to install the app to the merchant's store.

I recognize this is confusing due to the overlapping terminology, but hopefully this cleared things up a little.
