### ISSUE TITLE
[Bug]: Specifying `--host` causes live theme to be serve with `shopify theme dev` 

### ISSUE THREAD

**Issue by patquig** [Shopify/cli#3663]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Running command to serve development environment such as `shopify theme dev -s=<STORE-NAME> --theme-editor-sync --theme=<THEME-ID> --host=192.168.0.245 --port=7323` should result in a local instance running the code/theme in the work folder you're running the command from.

### Actual behavior

Local instance serves the stores current live theme instead of the theme/codebase you are currently working from. The public preview link shows the correct theme. If you remove the `--host` then the content is served from `127.0.0.1` and shows the correct theme.

[See video](https://cdn.shopify.com/videos/c/o/v/55f9345c0fbf46838a41bb1bb005dcf6.mp4)

### Verbose output

```shell
n/a
```

### Reproduction steps

1. Include `--host` in `shopify theme dev` command with valid IP
2. Open locally served link
3. Observe the live theme is shown

### Operating System

Mac OS 14.4.1 (23E224)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v21.5.0

**Comment by jamesmengo** [comment]
Hey! Looking into this.

We haven't made any changes to the `dev` command or touched any of the code that it relies on in this most recent release, but I do see some other issues related to theme previews starting yesterday. I have a strong suspicion that these are connected.

While we investigate, if you're able to provide any of this additional information it could help us address this faster :) 
1) Is this still occurring?
  - We saw issues related to theme previews that correlate in timestamp which have since been resolved
2) If so, could you try this on chrome + any additional browsers?

**Comment by jamesmengo** [comment]
This issue doesn't seem to be coming from CLI, so we'll have to dig deeper in upstream services to find what may have caused this.

In the meantime, please use the workaround by appending the value for `preview_theme_id` to your query params

<img width="556" alt="image" src="https://github.com/Shopify/cli/assets/35415298/b19052e9-0468-4895-89bc-c8e88ae2cbfb">

In the above example, the workaround URL would be
`http://127.0.0.1:9292/?preview_theme_id=<PREVIEW_THEME_ID>`

**Comment by patquig** [comment]
> Hey! Looking into this.
> 
> We haven't made any changes to the `dev` command or touched any of the code that it relies on in this most recent release, but I do see some other issues related to theme previews starting yesterday. I have a strong suspicion that these are connected.
> 
> While we investigate, if you're able to provide any of this additional information it could help us address this faster :)
> 
> 1. Is this still occurring?
> 
> * We saw issues related to theme previews that correlate in timestamp which have since been resolved
> 
> 2. If so, could you try this on chrome + any additional browsers?

@jamesmengo Aplogies for the delayed response. 

Yes still occurring. Tried on Chrome, Arc, Firefox (standard and dev vesrion), Safari, Edge. Happens on my Macbook and Windows PC.

Just tried the workaround but still results in the live theme being served.

**Comment by jamesmengo** [comment]
Thanks for the info @patquig, this is on the radar on being looked into :)

**Comment by olach** [comment]
I'm also experiencing this issue with the CLI. I'm not using any flags, just `shopify theme dev`. The local instance serves the current live theme instead of the theme you are currently working on. 

I tried the `?preview_theme_id=<PREVIEW_THEME_ID>` workaround but that does not solve the issue for me unfortunately.

**Comment by sigveio** [comment]
@jamesmengo our workaround for now was to build a new dev env that could function without the `--host`. But a new issue since the last 24h or so is that we often have to save the file / trigger a sync update twice in order to see the change. And it doesn't seem very consistent either. So it's quite frustrating / slow to work with..

**Comment by mgmanzella** [comment]
👋  this issue is actively being worked on, i know it's frustrating but please be patient as we work on a fix. thank you!
