### ISSUE TITLE
Shopify-CLI: "shopify login" command not working

### ISSUE THREAD

**Issue by Sowmiya-Arunachalakumar** [Shopify/cli#3861]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

This app was in working condition. But now, after i upgrade my shopify cli to the recent version, i was unable to run the app in my local, which says error as below

[push] ╭─ error ──────────────────────────────────────────────────────────────────────╮
[push] │                                                                              │
[push] │  Failed to prompt:                                                           │
[push] │                                                                              │
[push] │  Command login not found. Did you mean auth logout?                          │
[push] │                                                                              │
[push] │  This usually happens when running a command non-interactively, for example  │
[push] │   in a CI environment, or when piping input from another process.            │
[push] │                                                                              │
[push] │  To resolve this, specify the option in the command, or run the command in   │
[push] │  an interactive environment such as your local terminal.                     │
[push] │                                                                              │

When i looked through the doc, i saw that shopify login command was removed. Need to use 

> shopify theme dev --store "shop.myshopify.com"

as a command to login to store.

Here is my code am using in Shopify.js within my theme repo, please let me know the exact structure or format to update the command in this file 

await shopify({
  command: "login",
  env: {
    SHOPIFY_SHOP: process.env.PERMANENT_DOMAIN,
    SHOPIFY_PASSWORD: process.env.PASSWORD,    
  }
});

### Actual behavior

unable to run my theme in local with npm run dev.

### Verbose output

```shell
NA
```

### Reproduction steps

1.
2.
3.NA

### Operating System

mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.57.0

### Node version (run `node -v` if you're not sure)

v16.20.2

**Comment by isaacroldan** [comment]
Hi @Sowmiya-Arunachalakumar , do you mean that `shopify theme dev --store "shop.myshopify.com"` didn't work for you?

**Comment by Gamer09CF** [comment]
Hello! I have the same problem and the result of `shopify theme dev --store "shop.myshopify.com"` is: `To run this command, log in to Shopify.
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Authorization is required to continue, but the current environment does     │
│  not support interactive prompts.                                            │
│                                                                              │
│  To resolve this, specify credentials in your environment, or run the        │
│  command in an interactive environment such as your local terminal.          │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

`
and `shopify login` doesn't work and gives me: `╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Failed to prompt:                                                           │
│                                                                              │
│  Command login not found. Did you mean hydrogen login?                       │
│                                                                              │
│  This usually happens when running a command non-interactively, for example  │
│   in a CI environment, or when piping to or from another process.            │
│                                                                              │
│  To resolve this, specify the option in the command, or run the command in   │
│  an interactive environment such as your local terminal.                     │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

`. can someone please help? I am also on macOS 14.5.
