### ISSUE TITLE
[Feature]: Use yarn resolutions to fix typescript errors in newly scaffolded checkout ui extension

### ISSUE THREAD

**Issue by rhyek** [Shopify/cli#395]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

When scaffolding a new extension I get the TypeScript errors mentioned in https://github.com/Shopify/remote-ui/issues/153 (in VSCode, not with yarn dev).
The solution proposed in that issue is to add this to the package.json and yarn install:
```json
{
  ...
  "resolutions": {
    "@types/react": "17.0.30"
  }
}
```

### Motivation

Should not have TypeScript errors in newly created extension project.

**Comment by jamesvidler** [comment]
Related to this issue is: https://github.com/Shopify/shopify-cli-extensions/pull/315. We attempted to put in a fix for this in CLI 2. 

One additional note to consider is that `resolutions` are only for `yarn`. I think we would need to conditionally use `resolutions` if the package manager is `yarn`, or `overrides` if the package manager is `npm` or `pnpm`.
