### ISSUE TITLE
[Feature]: Upload A Selected File or Section In Shopify Theme

### ISSUE THREAD

**Issue by easonduan1** [Shopify/cli#4193]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

In some cases of developing themes, our current directory is associated with two environments (test environment and production environment). Although they correspond to the same directory, the online files of the two environments are used differently. We only want to use some files in the test environment, and some in the production environment. Therefore, we often need to upload different or specific code files to different environments. Therefore, if it is possible to support uploading specific files to the online environment, just like theme deploy + specific file path in theme kit. This feature is very helpful for my development, and it is also an important reason why I can't give up theme kit and use Shopify theme cli!

### Motivation

This feature is very helpful for my development, and it is also an important reason why I can't give up theme kit and use Shopify theme cli and I think this is also the reason why many people are still using theme kit !

**Comment by easonduan1** [comment]
I would love to try to add this functionality to a Shopify theme if possible!

**Comment by rcasimmons** [comment]
I see this more as a 'process' issue than an issue with CLI.

This seems like it could simply be overcome by having two GIT branches? We also have files that are specific to production and testing but this is sorted by way of simply having different git branches.

In addition, CLI does support prod/test environment flags.

In any case I see no reason anyone should be using ThemeKit in 2024 - CLI is a much more streamlined and safer approach to theme development.

I wouldn't see any benefit in this feature.

**Comment by jamesmengo** [comment]
Hey @easonduan1!

I don't know your full workflow so please feel free to correct me if I've missed something, my initial impression is that the simplest approach to achieve what you are asking for is to follow @rcasimmons' suggestion of maintaining a `test` and `prod` branch separately.

This will prevent you from needing to manually configure specific paths that you want to push and should be a less error-prone approach.

If you do, however, want to maintain a single branch, might I suggest looking into the `theme push` [command](https://shopify.dev/docs/api/shopify-cli/theme/theme-push)? You can specify specific files to upload using `--only`, `--ignore`, and you can specify the theme via flags as well.

Another alternative would be to configure two different `shopifyignore` [files](https://shopify.dev/docs/storefronts/themes/tools/cli#excluding-files-from-shopify-cli) and switch them out as you like before pushing your theme.

Let me know if that helps, or if you need more clarification!

Since I believe what you are asking for is already achievable, I'm going to close this issue for the moment, but feel free to open it again with clarification if you disagree!

Thanks for helping improve the CLI!
