### ISSUE TITLE
[Bug]: Shopify theme dev - already compiled asset javascript gets mangled

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/cli#4525]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Scripts work as normal

### Actual behavior

Despite having .min.js in the filename the script appears to get modified when served via the CLI. I'm guessing in attempt to minimise it? 
I've attached the before and after of what's happening so that you can compare. 

[before.txt](https://github.com/user-attachments/files/17130077/before.txt)
[after.txt](https://github.com/user-attachments/files/17130078/after.txt)

Differences.. 

Code chopped off / removed
![Image](https://github.com/user-attachments/assets/5d424bf9-1b3a-4e65-b443-e74d25ee28de)

Special Characters broken
![Image](https://github.com/user-attachments/assets/f217cff7-70da-4b87-9a1b-29ade93b6dc0)

### Verbose output

N/A

### Reproduction steps

1.  Add before.txt file as JS to theme
2.  Look at JS loaded in the browser
3.  See differences

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.67.1

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

22.7.0

**Comment by sillycube** [comment]
The same. The CLI chopped my code. My original code:
_esModule",{value:!0}),e}({},Vue);

When I preview the dev store in http://127.0.0.1:9293, the code in my app extension becomes:
_esModule",{value:!0}),e}({},Vu

As a result, it gives me a syntax error because the ')' is missing. I am using Mac OS with CLI of 3.67.2, node v22.5.1. 

I am migrating from a remote CLI login to a local CLI ([issue: 4495](https://github.com/Shopify/cli/issues/4495.)). And it gives me this issue again. Please give me a way out
