### ISSUE TITLE
[Feature]: Env variables support

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/cli#4587]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

I thought it would be nice to have env variables support similar to Vite (https://vite.dev/guide/env-and-mode) - those can be set in .env file or in vite config. In Shopify CLI I imagine that they could be set on shopify.app.toml level and possibly in .env file. Then it should replace all `import.meta.env...` in extension files. 

### Motivation

Need simpler way to store API endpoint variable depending on the environment (dev/staging/production)

**Comment by isaacroldan** [comment]
I'm aware of the lack of documentation for this, sorry about that. But this is stable and shouldn't change in the short term.

**Comment by isaacroldan** [comment]
Unfortunately that's not possible. They way it works is that we pass the contents of `process.env` (all environment variables) to `esbuild`. And then `esbuild` does the replacement while building the extension. So we don't know which specific values are being replaced.

Since it has been solved, i'll close the issue :)
