### ISSUE TITLE
[Feature]: copy install link to clipboard

### ISSUE THREAD

**Issue by zoultrex** [Shopify/cli#485]
### What type of project(s) will this request affect?

app

### What type of change do you want to see?

New feature

### Overview

Please add an extra flag after `shopify app dev` so we can just paste the install URL to the browser
Suggestion: `shopify app dev --clipboard` 

### Motivation

Since the ngrok URL changes every time you restart the server, it would be very handy to have the url on clipboard.
Since this is not the default behavior for most cases, I though adding it through a flag would be better.
Copy paste from terminal is not great, specially when working on mac sometimes I select then git control C which kills the server running, hence having it already on clipboard would be great.

**Comment by gonzaloriestra** [comment]
Thanks for the suggestion! We are working to improve the UI, especially for the dev command, so we'll take this into account. cc: @MeredithCastile

In the meanwhile:
- On iterm2 you can also right click to copy the link
- You can create your own permanent tunnel and pass it with the [`--tunnel-url` flag](https://shopify.dev/apps/tools/cli/commands#flags)
- Next week we'll remove the need of the tunnels in some cases (apps without extensions), stay tuned!

Btw, Iv'e transferred the issue, since https://github.com/Shopify/shopify-cli contains the old version (2.x).

**Comment by pixelchutes** [comment]
If you're on macOS + using iTerm2, you can also hold down <kbd>Command</kbd> key to make hyperlinks in the terminal _clickable_:

<img width="806" alt="iterm_clickable_link__hold_command_key_" src="https://user-images.githubusercontent.com/352182/191575887-7d4b4ba3-ebd0-4f80-aea2-2d49d9b8fd0c.png">

**Comment by zoultrex** [comment]
Thanks for the reply Gonzalo, I'll keep an eye for the next updates
I do use the tunnel already, I pay ngrok so I make a tunnel with the same subdomain so I don't have to keep updating the webhooks

I use mac for 2 years now and I had no idea I could right click links on the terminal, thanks for the tip


> Thanks for the suggestion! We are working to improve the UI, especially for the dev command, so we'll take this into account. cc: @MeredithCastile
> 
> In the meanwhile:
> 
> * On iterm2 you can also right click to copy the link
> * You can create your own permanent tunnel and pass it with the [`--tunnel-url` flag](https://shopify.dev/apps/tools/cli/commands#flags)
> * Next week we'll remove the need of the tunnels in some cases (apps without extensions), stay tuned!
> 
> By the way, I've transferred the issue, since https://github.com/Shopify/shopify-cli contains the old version (2.x).
