### ISSUE TITLE
[Bug]: Cannot install packages

### ISSUE THREAD

**Issue by andershagbard** [Shopify/cli#4901]
Getting this error when running `pnpm install` in the main branch.

```
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @shopify/theme@3.70.0

This error happened while installing a direct dependency of /Users/anderssogaard/Projects/shopify-cli/packages/app

The latest release of @shopify/theme is "3.58.2".
```

**Comment by gonzaloriestra** [comment]
Hi! The `@shopify/cli` package now includes `theme` and `ui-extensions-test-utils`, so you only need that one.

You can find more information here: https://shopify.dev/docs/apps/build/cli-for-apps#switch-to-a-global-executable-or-local-dependency

**Comment by andershagbard** [comment]
@gonzaloriestra It is still not fixed.

Steps to replicate:
1. Forge this (https://github.com/Shopify/cli) repository
2. Run `pnpm install`

**Comment by gonzaloriestra** [comment]
Oops, you are right. Let us investigate...

**Comment by gonzaloriestra** [comment]
Are you using pnpm v9? I think that's the issue. It only works with v8 for now, as explained [here](https://github.com/Shopify/cli/blob/main/docs/cli/get-started.md#requirements).

We are not releasing other packages than `cli`, because that one now includes the rest. Pnpm must take the dependencies locally, and that only works with v8.

**Comment by andershagbard** [comment]
Makes sense. I think this can be fixed by adding `link-workspace-packages=true` to `.npmrc` then

**Comment by gonzaloriestra** [comment]
Thanks for the suggestion! 👏 

I've created a [PR to enable it](https://github.com/Shopify/cli/pull/4931), so PNPM v9 is also compatible.
