### ISSUE TITLE
Support retrieving releases for private repositories

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#6]
[Reference](https://github.com/Shopify/shopify-cli-next/issues/239)

### Overview

The `github` module has a method for getting releases for a repository. We can read the credentials from the environment and use them in HTTP headers to support access to private repositories.

### Motivation

More context https://github.com/Shopify/shopify-cli-next/pull/220#pullrequestreview-948295904

**Comment by craigmichaelmartin** [comment]
Hey @pepicrft! It seems like this issue can be pared down to just support for retrieving releases. Working with a private template repo already works when GitHub credentials are configured, and issue #4 addresses when no GitHub credentials are configured.

As for support for retrieving releases, do you have any thoughts on the URL representation of this? It looks like the CLI has its own URL convention for describing branches using a hash value:

https://github.com/Shopify/cli/blob/1e0c7a7f89558afc5070f2c48f8b7af5e2988315/packages/cli-kit/src/github.ts#L93

So, for example, when describing the `cli_three` branch of Shopify's `shopify-app-template-node` repo, using https://github.com/Shopify/shopify-app-template-node#cli_three rather than GitHub's URL of https://github.com/Shopify/shopify-app-template-node/tree/cli_three

Is there a similar convention we want to use for releases?

Is there interest in adding support for using GitHub's URL when specifying branch (eg https://github.com/Shopify/shopify-app-template-node/tree/cli_three) or release (EG https://github.com/nodejs/node/releases/tag/v18.4.0) in addition to the current hash convention for branch and the TBD convention (or none) for release?

**Comment by pepicrft** [comment]
Note that to get releases we go through [GitHub'S REST API](https://github.com/Shopify/shopify-cli-next/blob/main/packages/cli-kit/src/github.ts#L41) and not through the `git` repository, so https://github.com/Shopify/cli/issues/4 addresses `git` operations. Git provides a command, `credential-store`, that you can use to retrieve any system's credentials. [Here's](https://github.com/Shopify/dev/blob/1dd2e9e2fa123d48b93e5928b20b01294ef75e6f/lib/dev/helpers/api/github/authenticator.rb#L139) an example of how `dev` does it. Once you get the credential, you can include them in an `Authorization` header in the requests. We can also allow developers to pass an authentication token through an environment variable, `SHOPIFY_CLI_GITHUB_TOKEN`:

```ts
// github.ts

async function getCredentials(): Promise<string> {

}
```

> As for support for retrieving releases, do you have any thoughts on the URL representation of this? It looks like the CLI has its own URL convention for describing branches using a hash value:

We already have [a function](https://github.com/Shopify/shopify-cli-next/blob/main/packages/cli-kit/src/github.ts#L35) to get the latest release and that's sufficient for our needs. In the future we can add new client-side functions as needed.
