### ISSUE TITLE
[Feature]: Ability to upload theme extensions from a `/dist` folder

### ISSUE THREAD

**Issue by NexPB** [Shopify/cli#867]
### What area(s) will this request affect?

Extension, Deployment

### What type of change do you want to see?

Substantial change to existing feature

### Overview

A way to deploy a theme extensions (or other extensions) from a specific folder that is generated after a build command has been executed.

### Motivation

This is easily achiveable with CLI 2.x using a custom command e.g. `npm run build` (which generates a folder named `/dist`) and then running a command like `cd dist` and `shopify extension push`.

This allows us to use rollup or equivalent before the extension is pushed.

**Comment by NexPB** [comment]
@matteodepalo afaik @Shopify/theme-developer-tools seems to be for themes in general this is for an existing app where I want to publish theme extensions, I was trying to migrate to Shopify CLI 3.x from 2.x

**Comment by karreiro** [comment]
👋 Hi @matteodepalo,

I don't think that @Shopify/theme-developer-tools has so much context on that.

My understanding is that this issue is a proposal to support a different directory structure in a app. Thus, the `app deploy` command (which is the new command that replaces `shopify extension push`) would support deploying an extension from a `/dist` directory. Is that correct, @NexPB?

**Comment by gonzaloriestra** [comment]
As explained [here](https://shopify.dev/apps/tools/cli/structure#build-and-deploy-process), when running deploy, the CLI is building the extensions in a temporary directory.

So to achieve this, I guess we could add a new optional field to the `shopify.*.extension.toml` files like `deploy_directory = "dist"` to use that content when present instead of building.

cc: @stephszeto

**Comment by NexPB** [comment]
Bump

**Comment by stephszeto** [comment]
> So to achieve this, I guess we could add a new optional field to the shopify.*.extension.toml files like deploy_directory = "dist" to use that content when present instead of building

This makes sense to me - will see where we can slot this into our roadmap! Thanks for raising!

**Comment by amcaplan** [comment]
still relevant

**Comment by amcaplan** [comment]
Please don't close!

**Comment by NexPB** [comment]
Today we could not publish a theme-extension release for one of our apps (since the admin dashboard flow does not detect the latest changes when we make a release), some help would be appreciated.

This app still relies on the old shopfy cli 2.0 flow which easily supported this flow... some urgency would be appreciated :')

**Comment by NexPB** [comment]
Hasn't been completed yet :/

**Comment by pauldraper** [comment]
Well it keeps being marked completed.....

**Comment by pauldraper** [comment]
Still relevant.

**Comment by c-e-daly** [comment]
@pauldraper is your purpose here to publish/deploy just one extension rather than several?  If so - we are in the same boat.  Would like to see that functionality.

**Comment by pauldraper** [comment]
No, that's not my purpose.

My purpose is running TS/rollup/webpack on scripts
