### ISSUE TITLE
When I Run 'Shopify Theme Dev' Get A Error In Command Prompt

### ISSUE THREAD

**Issue by Zardw** [Shopify/cli#951]
![image](https://user-images.githubusercontent.com/117419340/208334654-50195eaa-e9c3-4964-b12d-5b654a5ddd95.png)

I submitted this question in the shopify community, but nobody replied to me.

**Comment by gonzaloriestra** [comment]
Hi! I've just tried the `theme dev` command with the latest version (v3.29) in Windows and it works for me.

However, looking at the stacktrace, it seems that it's crashing when trying to read your local storage. Could you please share it? You should find it in `C:\Users\zardw\AppData\Roaming\shopify-cli-kit-nodejs\Config\config.json` (you can remove or modify sensitive info like tokens).

As a workaround, I'd try to run `shopify theme dev --store your-store` because that would overwrite the file, or directly to remove it.

**Comment by Zardw** [comment]
Thanks for your advice, I open this file, I found it was garbled. I can run the command successfully after deleting it.
