### ISSUE TITLE
[Feature]: Allowing to push to multiple store

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#973]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

Thanks a lot for the extra features added to Theme CLI. This make it usable and we have finally been able to ditch ThemeKit completely from our build pipeline.

The only (albeit minor) thing I miss from the theme kit is to be able to push to multiple store (in our case, we have multiple demo stores for our themes).

It would be nice if the command could accept multiple preset:

```
shopify theme push --preset demo-1 --preset demo-2 --preset demo-3
```

For now, we need to run multiple commands sequentially, which takes a bit of time when the theme becomes large:

```
shopify theme push --preset demo-1  && shopify theme push --preset demo-2 && shopify theme push --preset demo-3
```

Thanks :)

### Motivation

Bring parity with this old ThemeKit feature.

**Comment by karreiro** [comment]
👋 @stephszeto 

Adding @amcaplan in the loop, as he's working care of the [presets prototype](https://github.com/Shopify/cli/issues/794#issuecomment-1362573338) and have the context to understand if we may support multiple occurrences of the `--preset` flag (or equivalent).

**Comment by amcaplan** [comment]
I think this is more likely to be implemented as accepting multiple `--theme` params for the `theme push` command. WDYT @karreiro?

**Comment by bakura10** [comment]
Still relevant.

**Comment by karreiro** [comment]
👋 @bakura10,

Could you please clarify this question from my last comment:

> Would be enough to support multiple `--theme` flags at the `shopify theme push` command? Or, does the use case you're sharing require multiple ~`--preset`~`--environment` flags, because themes are pushed on multiple stores?

I'm asking because my understanding is that supporting multiple `--theme` flags wouldn't be enough, because the desired feature about executing a command on multiple environments (so users can push a theme on multiple stores).

Am I missing something?

Thank you for reporting this 🙇

**Comment by amcaplan** [comment]
This is a really interesting situation. I assume you're referring to the `--allenvs` flag. Which is a nice feature, but also a bit problematic as it only allows 1 or all, rather than a selected subset.

Given that `--environment` is meant to characterize the entire command run, potentially including other flags, I don't think we'll support this as described.

Additionally, keep in mind that there are commands where if we supported this, it would create nonsensical situations, such as `theme pull` pulling from multiple themes. What should the end product look like in such a case? Hence, I think this should be something `push`-specific.

That said, I like the idea of using the configured environments to drive parallel operations.

What if, for this specific command, we created a new `--environments` flag (exclusive to `--environment`) which would run the command's implementation in parallel for each specified environment? I think we could reuse most of the existing environments logic (basically just call [this](https://github.com/Shopify/cli/blob/de037b63072eddc9472079ab0dd722d8c2d853ff/packages/cli-kit/src/public/node/base-command.ts#L64)) to apply the relevant environment to each run.

@karreiro WDYT?

**Comment by karreiro** [comment]
Great catch, @kenji-twp! Thank you. If each environment is configured in a different store, parallelizing commands would indeed accelerate the execution (as each one would have a different rate limit).

Also, an alternative to have that (on Unix) is using a single ampersand, like this:`shopify theme push -e env1 & shopify theme push -e env2` :)
